# Generated by Django 5.0 on 2023-12-12 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_uploadedfile_user_alter_uploadedfile_file'),
        ('inventory_app', '0003_remove_inventory_item_item_inventory_item_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='proof-of-purchase/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='inventory_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_app.inventory_item'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
