services:
  db:
    image: postgres
    volumes: # Development only named-volume configuration for data persistence
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env/.postgres.env
  api:
    build: back-end
    command: python manage.py runserver 0.0.0.0:8000
    volumes: # Development only volume mount configuration for immediate updates
      - ./back-end:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env/.django.env
    depends_on:
      - db
  frontend:
    build: front-end
    command: npm run dev
    volumes: # Development only volume mount configuration for immediate updates
      - ./front-end:/app
    ports:
      - "80:5173"

volumes:
  postgres_data: