# Generated by Django 5.0 on 2023-12-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='all_items',
        ),
    ]
