name: Backend CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: github_actions
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install binary dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            gcc \
            postgresql-client \
            tesseract-ocr \
            poppler-utils \
            libgli

      - name: Upgrade pip/install dependencies
        run: |
          pip install --upgrade pip
          pip install -r back-end/requirements.txt

      - name: Run migrations
        run: |
          cd back-end
          python manage.py migrate

      - name: Run Tests
        run: |
          cd back-end
          python manage.py test
