name: Backend CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Upgrade pip/install dependencies
        run: |
          pip install --upgrade pip
          pip install -r back-end/requirements.txt

      - name: Run Migrations
        run: |
          cd back-end
          python manage.py migrate

      - name: Run Tests
        run: |
          cd back-end
          python manage.py test
